services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    # volumes:
    #   - ./:/app
    volumes:
      - ./src/main/resources:/app/src/main/resources:rw  # resourcesディレクトリのみをマウント（静的ファイルとテンプレートの即時反映）
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      
volumes:
  postgres-data: